### ISSUE TITLE
Light bulb renamed in Hue app not reflected in Hue-Advanced

### ISSUE THREAD

**Issue by waynelian** [claytonjn/SmartThingsPublic#35]
Recently I had few light bulbs giving me issues and I was swapping them around, hence I did rename for few of them such as:
- "Kitchen light" renamed to "Spoilt (Kitchen light)"
- "Living room light" renamed to "Kitchen light"
- "Spare light bulb 1" renamed to "Living room light" 
  etc..

The changes do not reflect in Hue-Advanced. So when I go to Hue-Advanced (Connect) smartapp, it suddenly increased my light bulbs count and I have two "Living room light" and two "Kitchen light".

**Comment by claytonjn** [comment]
When you say it increased your light bulb count, do you mean when you go into the Hue Advanced (Connect) SmartApp where you select lights, groups, etc., or did it actually add the lights as new devices automatically?

**Comment by waynelian** [comment]
It was in the Hue Advanced (Connect) Smartapp, both the original name and the new name are listed as devices, as I couldn't identify which is correct one so I ticked all of them, and manually delete it in ST devices list. The wrong one can no longer be controlled, that's why I managed to identify the correct one.

**Comment by claytonjn** [comment]
Are you at all familiar with the Hue API debug tool? I'd like to see what the actual Hue hub reports.

**Comment by waynelian** [comment]
You can point me a guide or link for the tool, I can pick it up no worries. :)

**Comment by claytonjn** [comment]
Start here: http://www.developers.meethue.com/documentation/getting-started
Then once you're set up, use /api/<username>/lights for URL and hit the GET button. In the response, look to see if you have the bulbs duplicated in there as well.

**Comment by waynelian** [comment]
It returned 12 lights, what I observed is that the numbers returned not in incremental sequence, those deleted one is not in returned list where  the Hue-Advanced Smartapp returned 16.

`"10": {
        "state": {
            "on": false,
            "bri": 0,
            "ct": 0,
            "alert": "none",
            "colormode": "hs",
            "reachable": false
        },
        "type": "Color temperature light",
        "name": "Guest bathroom light backup",
        "modelid": "FBL5601CT1.2",
        "manufacturername": "Feibit Inc co.  ",
        "uniqueid": "00:12:4b:00:07:5e:4f:ee-0b",
        "swversion": "1.0.2"
    },
    "14": {
        "state": {
            "on": false,
            "bri": 254,
            "hue": 42752,
            "sat": 15,
            "effect": "none",
            "xy": [
                0.3017,
                0.3165
            ],
            "ct": 162,
            "alert": "none",
            "colormode": "hs",
            "reachable": false
        },
        "type": "Extended color light",
        "name": "Spare kudled light",
        "modelid": "FB56-ZCW08KU1.0",
        "manufacturername": "Feibit Inc co.  ",
        "uniqueid": "00:12:4b:00:08:90:36:bb-0b",
        "swversion": "1.0.2"
    },`

**Comment by waynelian** [comment]
Is Hue-Advanced Smartapp taking the index as count as well? The last light returned is no 16.

`"16": {
        "state": {
            "on": true,
            "bri": 254,
            "hue": 34732,
            "sat": 232,
            "effect": "none",
            "xy": [
                0.3127,
                0.3203
            ],
            "ct": 153,
            "alert": "none",
            "colormode": "hs",
            "reachable": true
        },
        "type": "Extended color light",
        "name": "Kitchen second light",
        "modelid": "LCT001",
        "manufacturername": "Philips",
        "uniqueid": "00:17:88:01:00:ec:f5:85-0b",
        "swversion": "5.23.1.13452"
    }
}`

**Comment by waynelian** [comment]
Hi @claytonjn, just want to check whether you have chance to look into this issue?

I did live logging and discovered that it seem to add the bulbs that I have deleted from Hue Bridge.

9156de24-2794-4d3d-8069-280ebe82fed8  11:15:21 PM: trace Updated with settings: [updatePush:true, gitHubBranch:[Stable], selectedHue:00178829B649, selectedBulbs:[xxxx-id-xxxx/lights/3, xxxx-id-xxxx/lights/2, xxxx-id-xxxx/lights/9..... 

The lights 9, 11, 12, 13 were all removed from Hue Bridge already and it seem to be still being processed and added.

**Comment by claytonjn** [comment]
I've thought about why this is happening and how to fix it, I haven't had a chance to work on implementing in though. It's going to require careful and well thought out logic to prevent it from removing bulbs that should not in fact be removed. It's still on my radar, but when I focus on this I want to do it on a clear head and unfortunately I probably won't be able to do that for a while...lots of project at home and work.

**Comment by claytonjn** [comment]
@waynelian I actually moved one of my Hue lights this weekend, which prompted a rename. I renamed the bulb in the Hue app (v2), and then I renamed the device in SmartThings and changed the room it was in. I wanted to verify the behavior you described, where in the Hue Advanced (Connect) SmartApp the light was listed with the old and new names. 

When I opened Hue Advanced (Connect) and let it sit for a few minutes on the discovering bulbs page, it properly renamed the bulb and kept it selected. Therefore, from my testing, everything seemed to work properly.

I'm thinking that maybe you just didn't leave the SmartApp up on the bulb discovery page long enough for it to reflect the name changes? It stores everything in a variable that is updated based on discovery, but if discovery hasn't completed yet it will still keep the old values obviously, and if you proceed through the SmartApp it will reflect the old values in live logging because it doesn't know anything else.

**Comment by waynelian** [comment]
Hi @claytonjn , so sorry for the late reply, was tied up with works. I did leave the SmartApp up on bulb discovery page (~2-3 refresh) before I proceed. I believe the difference in the step you did is the deletion of bulb. Let me recap the steps here:
1. Open SmartThings mobile app, stop all the associated SmartApp activities related to the light bulb "Kitchen light".
2. Remove the "Kitchen light" from SmartThings devices.
3. Open Philips Hue mobile app, rename the light bulb "Kitchen light" to "Spoilt", "Living room light" to "Kitchen light" and "Spare light" to "Living room light". (I had all 3 bulbs already added in Hue, and I selected only "Kitchen light" and "Living room light" but excluded "Spare light" in SmartThings devies initially)
4. Open SmartThings mobile app, detect bulbs again and the duplicate name occurs in the refresh.

Meanwhile I did manage to slowly remove the wrong duplicate devices, so it's not urgent if you do not have time to look into this. :)

Thanks!
Wayne

**Comment by waynelian** [comment]
Hmm last night suddenly my SmartThings Hub unable to control all lights after receiving stable branch released notice, and from live logging I found that Hue-Advanced-Connect is not authorised. 

I did a discovery and reconnect back the Hue bridge, then suddenly everything working perfectly fine! 😮  It detected the correct number of light bulbs, everything working fine. Not sure if you have done something but this issue is resolved for me now. 🙇

**Comment by claytonjn** [comment]
Actually, I haven't changed anything. If you haven't heard about the recent issues from the SmartThings forum, they started deploying an update that cause corruption to state variables for some users. Hue Advanced (Connect) uses state variables to store the most recent update that it knows about, so when it polls and checks for updates if there's a different update date it notifies you. Because of the corruption, some users (myself included) got a notification that there was an update, when there really was not. I'm guessing something on the back end finally cleared up for you which is why the bulbs fixed themselves. 

Glad everything looks good on your end now though!
